#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # selected=$(find ~/Music/2026 ~/Music/08_2025 -mindepth 1 -maxdepth 1 -type d ! -name ".*" | $HOME/.fzf/bin/fzf --preview='onefetch --include-hidden {}' --preview-label="Git Info" --preview-window=down,65%)
    selected=$(find ~/Music/2026 ~/Music/08_2025 -mindepth 1 -maxdepth 1 -type d ! -name ".*" | $HOME/.fzf/bin/fzf --preview='tree -L 1' --preview-label="Structure" --preview-window=down,65%)
fi
if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name    
