#!/usr/bin/env bash
nav() {
    current=$(tmux display-message -p '#S')
    tmux list-sessions | grep -v "^$current:" | awk -F: '{print $1}' | "$HOME"/.fzf/bin/fzf --exit-0 --reverse | xargs tmux switch-client -t
}

fuzzy_sessions() {
    if [[ $# -eq 1 ]]; then
        selected=$1
    else
        selected=$(find ~/Gitchub ~/dotfiles ~/learning/**/ ~/hs/**/ ~/notes/**/ -mindepth 1 -maxdepth 1 -type d ! -name ".*" | "$HOME"/.fzf/bin/fzf)
    fi
    if [[ -z $selected ]]; then
        exit 0
    fi

    selected_name=$(basename "$selected" | tr . _)
    tmux_running=$(pgrep tmux)

    if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
        tmux new-session -s "$selected_name" -c "$selected"
        exit 0
    fi

    if ! tmux has-session -t="$selected_name" 2> /dev/null; then
        tmux new-session -ds "$selected_name" -c "$selected"
    fi

    tmux switch-client -t "$selected_name"    
}

window_list() {
    tmux lsw | grep -v "^$current:" | awk -F: '{print $1}' | "$HOME"/.fzf/bin/fzf --exit-0 --reverse | xargs tmux select-window -t
}

# Main script logic
case "$1" in
    warp)
        nav
        ;;
    nav)
        tmux-sessionizer
        # fuzzy_sessions
        ;;
    winwarp)
        window_list
        ;;
    *)
        echo "Usage: $0 { warp | nav | winwarp }"
        exit 1
        ;;
esac

exit 0
