-- require("toggleterm").setup{}
-- local status_ok, toggleterm = pcall(require, "toggleterm")
-- if not status_ok then
--     return
-- end

-- toggleterm.setup({
--     size = 20,
--     open_mapping = [[<c-t>]],
--     shade_filetypes = {},
--     shade_terminals = true,
--     shading_factor = 2,
--     persist_size = false,
--     close_on_exit = true,
--     float_opts = {
--         border = "curved",
--         winblend = 0,
--         highlights = {
--             border = "Normal",
--             background = "Normal",
--         },
--     },
-- })

-- function _G.set_terminal_keymaps()
--     local opts = {noremap = true}
--     vim.keymap.set('t', '<esc>', [[<C-\><C-n>]], opts)
--     vim.keymap.set('t', '<C-h>', [[<Cmd>wincmd h<CR>]], opts)
--     vim.keymap.set('t', '<C-j>', [[<Cmd>wincmd j<CR>]], opts)
--     vim.keymap.set('t', '<C-k>', [[<Cmd>wincmd k<CR>]], opts)
--     vim.keymap.set('t', '<C-l>', [[<Cmd>wincmd l<CR>]], opts)
-- end

