local Constants = {}

Constants = {

	lua_ls = {
		Lua = {
			diagnostics = {
				globals = { "vim" },
			},
		},
	},

	ensure_installed = {
		dap = {
			"bash-debug-adapter",
			-- 'codelldb',
			"debugpy",
			"delve",
			"go-debug-adapter",
			"java-debug-adapter",
			"js-debug-adapter",
			"php-debug-adapter",
		},
		lsp_config = {
			"lua_ls",
			"vimls",
			"marksman",
			"clangd",
			"neocmake",
			"html",
			-- 'hls',
			"cssls",
			"eslint",
			"tsserver",
			"bashls",
			"ansiblels",
			"dockerls",
			"yamlls",
			"ruff_lsp",
			"rust_analyzer",
			"ruby_ls",
			"pylsp",
			"gopls",
			"jdtls",
			"jsonls",
		},
		mason = {
			"bash-language-server",
			"clangd",
			"css-lsp",
			"emmet-ls",
			"eslint-lsp",
			"flake8",
			"gopls",
			"html-lsp",
			"json-lsp",
			"lua-language-server",
			"omnisharp",
			"pyright",
			"rust-analyzer",
			"shellcheck",
			"shfmt",
			"solargraph",
			"sqlls",
			"stylua",
			"texlab",
			"typescript-language-server",
			"yaml-language-server",
		},
		treesitter = {
			"astro",
			"bash",
			"c",
			"cmake",
			"cpp",
			"css",
			"diff",
			"fish",
			"gitignore",
			"go",
			"gomod",
			"gosum",
			"gowork",
			"html",
			"http",
			"java",
			"javascript",
			"jsdoc",
			"jsonc",
			"json",
			"lua",
			"luap",
			"markdown",
			"markdown_inline",
			"meson",
			"ninja",
			"nix",
			"norg",
			"org",
			"php",
			"python",
			"query",
			"regex",
			"rust",
			"scss",
			"sql",
			"svelte",
			"tsx",
			"typescript",
			"toml",
			"vim",
			"vimdoc",
			"yaml",
			"zig",
		},
	},
	-- disabling zone
	disabled = {
		lsp_config = {},
		mason = {},
		treesitter = {},
	},

	file_types = {
		"BufEnter *.c",
		"BufEnter *.cpp",
		"BufEnter *.cs",
		"BufEnter *.go",
		"BufEnter *.java",
		"BufEnter *.lua",
		"BufEnter *.py",
		"BufEnter *.rb",
		"BufEnter *.rs",
		"BufEnter *.ts",
	},
	icons = {
		dap = {
			expanded = "",
			collapsed = "",
			circular = "",
		},
		diagnostic = {
			Error = "",
			Hint = "",
			Info = "",
			Warn = "",
		},
		lsp_kinds = {
			Class = "",
			Color = "",
			Constant = "",
			Constructor = "",
			Enum = "",
			EnumMember = "",
			Event = "",
			Field = "",
			File = "",
			Folder = "",
			Function = "",
			Interface = "",
			Keyword = "",
			Method = "",
			Module = "",
			Operator = "",
			Property = "",
			Reference = "",
			Snippet = " ",
			Struct = "",
			Text = "",
			TypeParameter = "",
			Unit = "",
			Value = "",
			Variable = "",
		},
	},
	git = {
		add = "+",
		change = "",
		delete = "_",
		topdelete = "‾",
		changedelete = "~",
	},

	keymap_opts = {
		normal = {
			mode = "n",
			prefix = "<leader>",
			buffer = nil,
			silent = true,
			noremap = true,
			nowait = true,
		},
		visual = {
			mode = "v",
			prefix = "<leader>",
			buffer = nil,
			silent = true,
			noremap = true,
			nowait = true,
		},
	},

	completion = {
		source_mapping = {
			buffer = "󰦨",
			path = "/",
			nvim_lsp = "λ",
			luasnip = "⋗",
			vsnip = "V",
			nvim_lua = "Π",
		},
		sources = {
			{ name = "path" },
			{ name = "crates" }, -- crates.nvim plugin
			{ name = "nvim_lua" },
			{ name = "luasnip" },
			{ name = "vsnip" },
			{ name = "treesitter" }, -- treesitter integration
			-- { name = 'cmdline' },
			{
				name = "buffer",
				options = {
					get_bufnrs = function()
						return vim.api.nvim_list_bufs()
					end,
				},
			},
			{ name = "nvim_lsp" },
		},
	},
}

return Constants
